// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shipmentOrder.proto

package NishitDemo;

public final class ShipmentOrder {
  private ShipmentOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShipmentOrdersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NishitDemo.ShipmentOrders)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 shipmentId = 1;</code>
     * @return The shipmentId.
     */
    long getShipmentId();

    /**
     * <code>string shourceWarehouse = 2;</code>
     * @return The shourceWarehouse.
     */
    java.lang.String getShourceWarehouse();
    /**
     * <code>string shourceWarehouse = 2;</code>
     * @return The bytes for shourceWarehouse.
     */
    com.google.protobuf.ByteString
        getShourceWarehouseBytes();

    /**
     * <code>string destinationWarehouse = 3;</code>
     * @return The destinationWarehouse.
     */
    java.lang.String getDestinationWarehouse();
    /**
     * <code>string destinationWarehouse = 3;</code>
     * @return The bytes for destinationWarehouse.
     */
    com.google.protobuf.ByteString
        getDestinationWarehouseBytes();

    /**
     * <code>int32 noOfItems = 5;</code>
     * @return The noOfItems.
     */
    int getNoOfItems();

    /**
     * <code>int64 orderId = 6;</code>
     * @return The orderId.
     */
    long getOrderId();

    /**
     * <code>string sellerName = 7;</code>
     * @return The sellerName.
     */
    java.lang.String getSellerName();
    /**
     * <code>string sellerName = 7;</code>
     * @return The bytes for sellerName.
     */
    com.google.protobuf.ByteString
        getSellerNameBytes();

    /**
     * <code>int64 sellerId = 8;</code>
     * @return The sellerId.
     */
    long getSellerId();

    /**
     * <code>int64 customerId = 9;</code>
     * @return The customerId.
     */
    long getCustomerId();

    /**
     * <code>bool priority = 10;</code>
     * @return The priority.
     */
    boolean getPriority();
  }
  /**
   * Protobuf type {@code NishitDemo.ShipmentOrders}
   */
  public  static final class ShipmentOrders extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NishitDemo.ShipmentOrders)
      ShipmentOrdersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShipmentOrders.newBuilder() to construct.
    private ShipmentOrders(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShipmentOrders() {
      shourceWarehouse_ = "";
      destinationWarehouse_ = "";
      sellerName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShipmentOrders();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShipmentOrders(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              shipmentId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              shourceWarehouse_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              destinationWarehouse_ = s;
              break;
            }
            case 40: {

              noOfItems_ = input.readInt32();
              break;
            }
            case 48: {

              orderId_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              sellerName_ = s;
              break;
            }
            case 64: {

              sellerId_ = input.readInt64();
              break;
            }
            case 72: {

              customerId_ = input.readInt64();
              break;
            }
            case 80: {

              priority_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NishitDemo.ShipmentOrder.internal_static_NishitDemo_ShipmentOrders_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NishitDemo.ShipmentOrder.internal_static_NishitDemo_ShipmentOrders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NishitDemo.ShipmentOrder.ShipmentOrders.class, NishitDemo.ShipmentOrder.ShipmentOrders.Builder.class);
    }

    public static final int SHIPMENTID_FIELD_NUMBER = 1;
    private long shipmentId_;
    /**
     * <code>int64 shipmentId = 1;</code>
     * @return The shipmentId.
     */
    public long getShipmentId() {
      return shipmentId_;
    }

    public static final int SHOURCEWAREHOUSE_FIELD_NUMBER = 2;
    private volatile java.lang.Object shourceWarehouse_;
    /**
     * <code>string shourceWarehouse = 2;</code>
     * @return The shourceWarehouse.
     */
    public java.lang.String getShourceWarehouse() {
      java.lang.Object ref = shourceWarehouse_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shourceWarehouse_ = s;
        return s;
      }
    }
    /**
     * <code>string shourceWarehouse = 2;</code>
     * @return The bytes for shourceWarehouse.
     */
    public com.google.protobuf.ByteString
        getShourceWarehouseBytes() {
      java.lang.Object ref = shourceWarehouse_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shourceWarehouse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATIONWAREHOUSE_FIELD_NUMBER = 3;
    private volatile java.lang.Object destinationWarehouse_;
    /**
     * <code>string destinationWarehouse = 3;</code>
     * @return The destinationWarehouse.
     */
    public java.lang.String getDestinationWarehouse() {
      java.lang.Object ref = destinationWarehouse_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationWarehouse_ = s;
        return s;
      }
    }
    /**
     * <code>string destinationWarehouse = 3;</code>
     * @return The bytes for destinationWarehouse.
     */
    public com.google.protobuf.ByteString
        getDestinationWarehouseBytes() {
      java.lang.Object ref = destinationWarehouse_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationWarehouse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOOFITEMS_FIELD_NUMBER = 5;
    private int noOfItems_;
    /**
     * <code>int32 noOfItems = 5;</code>
     * @return The noOfItems.
     */
    public int getNoOfItems() {
      return noOfItems_;
    }

    public static final int ORDERID_FIELD_NUMBER = 6;
    private long orderId_;
    /**
     * <code>int64 orderId = 6;</code>
     * @return The orderId.
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int SELLERNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object sellerName_;
    /**
     * <code>string sellerName = 7;</code>
     * @return The sellerName.
     */
    public java.lang.String getSellerName() {
      java.lang.Object ref = sellerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sellerName_ = s;
        return s;
      }
    }
    /**
     * <code>string sellerName = 7;</code>
     * @return The bytes for sellerName.
     */
    public com.google.protobuf.ByteString
        getSellerNameBytes() {
      java.lang.Object ref = sellerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sellerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELLERID_FIELD_NUMBER = 8;
    private long sellerId_;
    /**
     * <code>int64 sellerId = 8;</code>
     * @return The sellerId.
     */
    public long getSellerId() {
      return sellerId_;
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 9;
    private long customerId_;
    /**
     * <code>int64 customerId = 9;</code>
     * @return The customerId.
     */
    public long getCustomerId() {
      return customerId_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 10;
    private boolean priority_;
    /**
     * <code>bool priority = 10;</code>
     * @return The priority.
     */
    public boolean getPriority() {
      return priority_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (shipmentId_ != 0L) {
        output.writeInt64(1, shipmentId_);
      }
      if (!getShourceWarehouseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, shourceWarehouse_);
      }
      if (!getDestinationWarehouseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destinationWarehouse_);
      }
      if (noOfItems_ != 0) {
        output.writeInt32(5, noOfItems_);
      }
      if (orderId_ != 0L) {
        output.writeInt64(6, orderId_);
      }
      if (!getSellerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sellerName_);
      }
      if (sellerId_ != 0L) {
        output.writeInt64(8, sellerId_);
      }
      if (customerId_ != 0L) {
        output.writeInt64(9, customerId_);
      }
      if (priority_ != false) {
        output.writeBool(10, priority_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (shipmentId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, shipmentId_);
      }
      if (!getShourceWarehouseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, shourceWarehouse_);
      }
      if (!getDestinationWarehouseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destinationWarehouse_);
      }
      if (noOfItems_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, noOfItems_);
      }
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, orderId_);
      }
      if (!getSellerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sellerName_);
      }
      if (sellerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, sellerId_);
      }
      if (customerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, customerId_);
      }
      if (priority_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, priority_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NishitDemo.ShipmentOrder.ShipmentOrders)) {
        return super.equals(obj);
      }
      NishitDemo.ShipmentOrder.ShipmentOrders other = (NishitDemo.ShipmentOrder.ShipmentOrders) obj;

      if (getShipmentId()
          != other.getShipmentId()) return false;
      if (!getShourceWarehouse()
          .equals(other.getShourceWarehouse())) return false;
      if (!getDestinationWarehouse()
          .equals(other.getDestinationWarehouse())) return false;
      if (getNoOfItems()
          != other.getNoOfItems()) return false;
      if (getOrderId()
          != other.getOrderId()) return false;
      if (!getSellerName()
          .equals(other.getSellerName())) return false;
      if (getSellerId()
          != other.getSellerId()) return false;
      if (getCustomerId()
          != other.getCustomerId()) return false;
      if (getPriority()
          != other.getPriority()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SHIPMENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getShipmentId());
      hash = (37 * hash) + SHOURCEWAREHOUSE_FIELD_NUMBER;
      hash = (53 * hash) + getShourceWarehouse().hashCode();
      hash = (37 * hash) + DESTINATIONWAREHOUSE_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationWarehouse().hashCode();
      hash = (37 * hash) + NOOFITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getNoOfItems();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + SELLERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSellerName().hashCode();
      hash = (37 * hash) + SELLERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSellerId());
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerId());
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPriority());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NishitDemo.ShipmentOrder.ShipmentOrders parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NishitDemo.ShipmentOrder.ShipmentOrders prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NishitDemo.ShipmentOrders}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NishitDemo.ShipmentOrders)
        NishitDemo.ShipmentOrder.ShipmentOrdersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NishitDemo.ShipmentOrder.internal_static_NishitDemo_ShipmentOrders_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NishitDemo.ShipmentOrder.internal_static_NishitDemo_ShipmentOrders_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NishitDemo.ShipmentOrder.ShipmentOrders.class, NishitDemo.ShipmentOrder.ShipmentOrders.Builder.class);
      }

      // Construct using NishitDemo.ShipmentOrder.ShipmentOrders.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        shipmentId_ = 0L;

        shourceWarehouse_ = "";

        destinationWarehouse_ = "";

        noOfItems_ = 0;

        orderId_ = 0L;

        sellerName_ = "";

        sellerId_ = 0L;

        customerId_ = 0L;

        priority_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NishitDemo.ShipmentOrder.internal_static_NishitDemo_ShipmentOrders_descriptor;
      }

      @java.lang.Override
      public NishitDemo.ShipmentOrder.ShipmentOrders getDefaultInstanceForType() {
        return NishitDemo.ShipmentOrder.ShipmentOrders.getDefaultInstance();
      }

      @java.lang.Override
      public NishitDemo.ShipmentOrder.ShipmentOrders build() {
        NishitDemo.ShipmentOrder.ShipmentOrders result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public NishitDemo.ShipmentOrder.ShipmentOrders buildPartial() {
        NishitDemo.ShipmentOrder.ShipmentOrders result = new NishitDemo.ShipmentOrder.ShipmentOrders(this);
        result.shipmentId_ = shipmentId_;
        result.shourceWarehouse_ = shourceWarehouse_;
        result.destinationWarehouse_ = destinationWarehouse_;
        result.noOfItems_ = noOfItems_;
        result.orderId_ = orderId_;
        result.sellerName_ = sellerName_;
        result.sellerId_ = sellerId_;
        result.customerId_ = customerId_;
        result.priority_ = priority_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NishitDemo.ShipmentOrder.ShipmentOrders) {
          return mergeFrom((NishitDemo.ShipmentOrder.ShipmentOrders)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NishitDemo.ShipmentOrder.ShipmentOrders other) {
        if (other == NishitDemo.ShipmentOrder.ShipmentOrders.getDefaultInstance()) return this;
        if (other.getShipmentId() != 0L) {
          setShipmentId(other.getShipmentId());
        }
        if (!other.getShourceWarehouse().isEmpty()) {
          shourceWarehouse_ = other.shourceWarehouse_;
          onChanged();
        }
        if (!other.getDestinationWarehouse().isEmpty()) {
          destinationWarehouse_ = other.destinationWarehouse_;
          onChanged();
        }
        if (other.getNoOfItems() != 0) {
          setNoOfItems(other.getNoOfItems());
        }
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (!other.getSellerName().isEmpty()) {
          sellerName_ = other.sellerName_;
          onChanged();
        }
        if (other.getSellerId() != 0L) {
          setSellerId(other.getSellerId());
        }
        if (other.getCustomerId() != 0L) {
          setCustomerId(other.getCustomerId());
        }
        if (other.getPriority() != false) {
          setPriority(other.getPriority());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NishitDemo.ShipmentOrder.ShipmentOrders parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NishitDemo.ShipmentOrder.ShipmentOrders) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long shipmentId_ ;
      /**
       * <code>int64 shipmentId = 1;</code>
       * @return The shipmentId.
       */
      public long getShipmentId() {
        return shipmentId_;
      }
      /**
       * <code>int64 shipmentId = 1;</code>
       * @param value The shipmentId to set.
       * @return This builder for chaining.
       */
      public Builder setShipmentId(long value) {
        
        shipmentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 shipmentId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearShipmentId() {
        
        shipmentId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object shourceWarehouse_ = "";
      /**
       * <code>string shourceWarehouse = 2;</code>
       * @return The shourceWarehouse.
       */
      public java.lang.String getShourceWarehouse() {
        java.lang.Object ref = shourceWarehouse_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shourceWarehouse_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shourceWarehouse = 2;</code>
       * @return The bytes for shourceWarehouse.
       */
      public com.google.protobuf.ByteString
          getShourceWarehouseBytes() {
        java.lang.Object ref = shourceWarehouse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shourceWarehouse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shourceWarehouse = 2;</code>
       * @param value The shourceWarehouse to set.
       * @return This builder for chaining.
       */
      public Builder setShourceWarehouse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shourceWarehouse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string shourceWarehouse = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearShourceWarehouse() {
        
        shourceWarehouse_ = getDefaultInstance().getShourceWarehouse();
        onChanged();
        return this;
      }
      /**
       * <code>string shourceWarehouse = 2;</code>
       * @param value The bytes for shourceWarehouse to set.
       * @return This builder for chaining.
       */
      public Builder setShourceWarehouseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shourceWarehouse_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destinationWarehouse_ = "";
      /**
       * <code>string destinationWarehouse = 3;</code>
       * @return The destinationWarehouse.
       */
      public java.lang.String getDestinationWarehouse() {
        java.lang.Object ref = destinationWarehouse_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destinationWarehouse_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destinationWarehouse = 3;</code>
       * @return The bytes for destinationWarehouse.
       */
      public com.google.protobuf.ByteString
          getDestinationWarehouseBytes() {
        java.lang.Object ref = destinationWarehouse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinationWarehouse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destinationWarehouse = 3;</code>
       * @param value The destinationWarehouse to set.
       * @return This builder for chaining.
       */
      public Builder setDestinationWarehouse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destinationWarehouse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destinationWarehouse = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestinationWarehouse() {
        
        destinationWarehouse_ = getDefaultInstance().getDestinationWarehouse();
        onChanged();
        return this;
      }
      /**
       * <code>string destinationWarehouse = 3;</code>
       * @param value The bytes for destinationWarehouse to set.
       * @return This builder for chaining.
       */
      public Builder setDestinationWarehouseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destinationWarehouse_ = value;
        onChanged();
        return this;
      }

      private int noOfItems_ ;
      /**
       * <code>int32 noOfItems = 5;</code>
       * @return The noOfItems.
       */
      public int getNoOfItems() {
        return noOfItems_;
      }
      /**
       * <code>int32 noOfItems = 5;</code>
       * @param value The noOfItems to set.
       * @return This builder for chaining.
       */
      public Builder setNoOfItems(int value) {
        
        noOfItems_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 noOfItems = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNoOfItems() {
        
        noOfItems_ = 0;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <code>int64 orderId = 6;</code>
       * @return The orderId.
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>int64 orderId = 6;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(long value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 orderId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sellerName_ = "";
      /**
       * <code>string sellerName = 7;</code>
       * @return The sellerName.
       */
      public java.lang.String getSellerName() {
        java.lang.Object ref = sellerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sellerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sellerName = 7;</code>
       * @return The bytes for sellerName.
       */
      public com.google.protobuf.ByteString
          getSellerNameBytes() {
        java.lang.Object ref = sellerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sellerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sellerName = 7;</code>
       * @param value The sellerName to set.
       * @return This builder for chaining.
       */
      public Builder setSellerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sellerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sellerName = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSellerName() {
        
        sellerName_ = getDefaultInstance().getSellerName();
        onChanged();
        return this;
      }
      /**
       * <code>string sellerName = 7;</code>
       * @param value The bytes for sellerName to set.
       * @return This builder for chaining.
       */
      public Builder setSellerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sellerName_ = value;
        onChanged();
        return this;
      }

      private long sellerId_ ;
      /**
       * <code>int64 sellerId = 8;</code>
       * @return The sellerId.
       */
      public long getSellerId() {
        return sellerId_;
      }
      /**
       * <code>int64 sellerId = 8;</code>
       * @param value The sellerId to set.
       * @return This builder for chaining.
       */
      public Builder setSellerId(long value) {
        
        sellerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sellerId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSellerId() {
        
        sellerId_ = 0L;
        onChanged();
        return this;
      }

      private long customerId_ ;
      /**
       * <code>int64 customerId = 9;</code>
       * @return The customerId.
       */
      public long getCustomerId() {
        return customerId_;
      }
      /**
       * <code>int64 customerId = 9;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(long value) {
        
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 customerId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        
        customerId_ = 0L;
        onChanged();
        return this;
      }

      private boolean priority_ ;
      /**
       * <code>bool priority = 10;</code>
       * @return The priority.
       */
      public boolean getPriority() {
        return priority_;
      }
      /**
       * <code>bool priority = 10;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(boolean value) {
        
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool priority = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        
        priority_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NishitDemo.ShipmentOrders)
    }

    // @@protoc_insertion_point(class_scope:NishitDemo.ShipmentOrders)
    private static final NishitDemo.ShipmentOrder.ShipmentOrders DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NishitDemo.ShipmentOrder.ShipmentOrders();
    }

    public static NishitDemo.ShipmentOrder.ShipmentOrders getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShipmentOrders>
        PARSER = new com.google.protobuf.AbstractParser<ShipmentOrders>() {
      @java.lang.Override
      public ShipmentOrders parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShipmentOrders(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShipmentOrders> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShipmentOrders> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public NishitDemo.ShipmentOrder.ShipmentOrders getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NishitDemo_ShipmentOrders_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NishitDemo_ShipmentOrders_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023shipmentOrder.proto\022\nNishitDemo\"\314\001\n\016Sh" +
      "ipmentOrders\022\022\n\nshipmentId\030\001 \001(\003\022\030\n\020shou" +
      "rceWarehouse\030\002 \001(\t\022\034\n\024destinationWarehou" +
      "se\030\003 \001(\t\022\021\n\tnoOfItems\030\005 \001(\005\022\017\n\007orderId\030\006" +
      " \001(\003\022\022\n\nsellerName\030\007 \001(\t\022\020\n\010sellerId\030\010 \001" +
      "(\003\022\022\n\ncustomerId\030\t \001(\003\022\020\n\010priority\030\n \001(\010" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NishitDemo_ShipmentOrders_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NishitDemo_ShipmentOrders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NishitDemo_ShipmentOrders_descriptor,
        new java.lang.String[] { "ShipmentId", "ShourceWarehouse", "DestinationWarehouse", "NoOfItems", "OrderId", "SellerName", "SellerId", "CustomerId", "Priority", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
